site_name: Seyed Amir Alavi
site_author: Seyed Amir Alavi
site_url: https://samiralavi.github.io/
repo_url: https://github.com/samiralavi/samiralavi.github.io
repo_name: samiralavi.github.io

theme:
  name: material
  language: en
  icon:
    logo: material/contacts
  favicon: images/favicon.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: indigo
      accent: blue
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: red
      accent: red

  features:
    - navigation.instant
    - navigation.expand
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/samiralavi
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/seyed-amir-alavi/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UC57CLD9DWuUy2-rowVvj0Eg
  analytics:
    provider: google
    property: UA-181389079-1
  disqus: samiralavi

markdown_extensions:
  - meta
  - md_in_html
  - attr_list
  - toc:
      permalink: true
plugins:
  - search # necessary for search to work

nav:
  - index.md
  - activities.md
  - interests.md
  - publications.md
  - teaching.md
  - contact.md
  - Blog:
    - blog/buck_coverter/buck_converter_arduino.md
    - blog/iot_communication_patterns/iot_communication_patterns.md
