site_name: Seyed Amir Alavi's Personal Blog
site_author: Seyed Amir Alavi
site_url: https://samiralavi.github.io/
repo_name: samiralavi.github.io

theme:
  name: material
  custom_dir: overrides
  language: en
  icon:
    logo: material/contacts
  favicon: images/favicon.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: indigo
      accent: blue
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: red
      accent: red

  features:
    - navigation.expand
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/samiralavi
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/seyed-amir-alavi/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@Gear4Hackers
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/samiralavi_real
  analytics:
    provider: google
    property: G-NL4RPWEYBQ

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - meta
  - md_in_html
  - attr_list
  - toc:
      permalink: true

plugins:
  - search # necessary for search to work
  - blog:
      blog_toc: true
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags

nav:
  - index.md
  - activities.md
  - interests.md
  - publications.md
  - teaching.md
  - contact.md
  - blog/index.md

copyright: Copyright &copy; 2019 - 2023 Seyed Amir Alavi
